# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Test-Cocoapods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for Test-Cocoapods
  pod 'KLCPaaSSDK'
  pod 'KLMobileSDK'

end
